### ISSUE TITLE
fix Log encoding at initial file creation

### ISSUE THREAD

**Issue by 6uhrmittag** [6uhrmittag/todoist-progressbar#34]
`--- Logging error ---
Traceback (most recent call last):
  File "x__init__.py", line 994, in emit
    stream.write(msg)
  File "xcp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2023' in position 77: character maps to <undefined>`

**Comment by 6uhrmittag** [comment]
fixed in next release
